Trabalho 2 da disciplina Inteligência Computacional Aplicada - MLP e RBF

Como temos uma base pequena(174 instâncias), nessa solução aplicaremos validação cruzada

Carrega as bibliotecas

In [1]:
from sklearn.neural_network import MLPClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import KFold
from sklearn.model_selection import RepeatedKFold
from sklearn.decomposition import PCA

# Manipulação de dados
import numpy as np
import numpy.ma as ma
import pandas as pd
# Redes Neurais
#from tensorflow import keras
#from keras.models import Sequential
#from keras.layers import Dense, Dropout
#from keras.optimizers import RMSprop
# Plot
import matplotlib.pyplot as plt
%matplotlib inline
# Avaliação
from sklearn.metrics import classification_report, confusion_matrix

Carrega a base de dados

In [2]:

darwin = pd.read_csv("DARWIN.csv").to_numpy()
X = darwin[0:175,1:451]
y = darwin[0:175,451]
print(X)
print(y)

[[5160 1.25e-05 120.8041741 ... 1749.278166 296102.7676 144605]
 [51980 1.6e-05 115.3182382 ... 1504.768272 278744.285 298640]
 [2600 1.03e-05 229.9339973 ... 1431.443492 144411.7055 79025]
 ...
 [3830 8.36e-06 151.536989 ... 1915.573488 128727.1241 83445]
 [1760 7.96e-06 289.5181946 ... 1915.573488 128727.1241 83445]
 [2875 8.18e-06 235.7693499 ... 1915.573488 128727.1241 83445]]
['P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P'
 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P'
 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P'
 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P'
 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'P' 'H'
 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H'
 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H'
 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H'
 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H'

Normalização dos dados

In [3]:
X = 2*((X - np.amin(X,axis=0))/(np.amax(X,axis=0) - np.amin(X,axis=0))) - 1
print(np.amax(X))
print(np.amin(X))

1.0
-1.0


Redução de dimensionalidade aplicando PCA

In [4]:
PCA.n_features_ = 450
PCA.n_samples_ = 174
#pca = PCA(n_components= 'mle', svd_solver= 'full')
#pca = PCA(n_components= 0.9999, svd_solver= 'full')
pca = PCA(svd_solver= 'arpack')
pca.fit(X)

#print(pca.explained_variance_ratio_)

#print(pca.singular_values_)

X = pca.transform(X)



Gera a rede MLP

In [ ]:
#kf = KFold(n_splits=10)
kf = RepeatedKFold(n_splits=10,n_repeats=10)

loo = LeaveOneOut()
loo.get_n_splits(X)

mscore1 = 0.0;
mscore2 = 0.0;
mscore3 = 0.0;
cont = 0;
#clf = MLPClassifier(random_state=1, max_iter=300)

MLP1 = MLPClassifier(hidden_layer_sizes= 100, activation="relu", solver="adam",max_iter=300, random_state=1)
MLP2 = MLPClassifier(hidden_layer_sizes= 100, activation="logistic", solver="adam",max_iter=300, random_state=1)
MLP3 = MLPClassifier(hidden_layer_sizes= 100, activation="tanh", solver="adam",max_iter=300, random_state=1)
    

for train_index, test_index in kf.split(X):
#for train_index, test_index in loo.split(X):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    #print(X_train, X_test, y_train, y_test)

    MLP1.fit(X_train, y_train)
    MLP2.fit(X_train, y_train)
    MLP3.fit(X_train, y_train)

    MLP1.predict_proba(X_test)
    MLP2.predict_proba(X_test)
    MLP3.predict_proba(X_test)
    

    MLP1.predict(X_test)
    MLP2.predict(X_test)
    MLP3.predict(X_test)
    

    mscore1 = mscore1 + MLP1.score(X_test, y_test)
    mscore2 = mscore2 + MLP2.score(X_test, y_test)
    mscore3 = mscore3 + MLP3.score(X_test, y_test)
    cont = cont + 1

mscore1 = mscore1/cont
mscore2 = mscore2/cont
mscore3 = mscore3/cont

In [6]:


print("acurácia 1: ",mscore1)
print("acurácia 2: ",mscore2)
print("acurácia 3: ",mscore3)

acurácia 1:  0.8245424836601299
acurácia 2:  0.6607843137254902
acurácia 3:  0.7385620915032676


Gera a rede RBF

In [14]:
#kf = KFold(n_splits=10)
kf = RepeatedKFold(n_splits=10,n_repeats=10)

loo = LeaveOneOut()
loo.get_n_splits(X)

mscore4 = 0.0;
cont = 0;

kernel = 1.0 * RBF(1.0)
RBFC = GaussianProcessClassifier(kernel=kernel,random_state=0)

for train_index, test_index in kf.split(X):
#for train_index, test_index in loo.split(X):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    #print(X_train, X_test, y_train, y_test)

    RBFC.fit(X_train, y_train)

    RBFC.predict_proba(X_test)
    
    RBFC.predict(X_test)
    
    mscore4 = mscore4 + RBFC.score(X_test, y_test)
    cont = cont + 1

mscore4 = mscore4/cont

/usr/local/lib/python3.7/dist-packages/sklearn/gaussian_process/kernels.py:427: ConvergenceWarning: The optimal value found for dimension 0 of parameter k1__constant_value is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.
  ConvergenceWarning,


In [16]:
print(mscore4)

0.8532026143790842
